import React from 'react'
import '@testing-library/jest-dom/extend-expect'
import { render,screen } from '@testing-library/react'
import BlogInfoForm from './BlogInfoForm'
import userEvent from '@testing-library/user-event'