POST http://localhost:3003/api/users
Content-type: application/json


{
    "username": "hermion",
    "name": "hermion",
    "password": "hermion"

}

###

POST http://localhost:3003/api/login
Content-type: application/json


{
    "username": "hermion",
    "password": "hermion"

}

###

POST http://localhost:3003/api/blogs
Content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imhlcm1pb24iLCJpZCI6IjYzNTY0OTJiNDNlZmRkYjUwOTIzNzE4ZSIsImlhdCI6MTY2NjYxMTE2Mn0.k8g5wgKv9BUMVxbINDR6jtoY_ERaLqRBxbdVJuQv6LU
    
 {   
    "title": "stoot",
    "author": "marsipaan243",
    "url": "www",
    "likes": 999

}

###

DELETE http://localhost:3003/api/blogs/6356779c43efddb509237199
Content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imhlcm1pb24iLCJpZCI6IjYzNTY0OTJiNDNlZmRkYjUwOTIzNzE4ZSIsImlhdCI6MTY2NjYxMTE2Mn0.k8g5wgKv9BUMVxbINDR6jtoY_ERaLqRBxbdVJuQv6LU

###

GET http://localhost:3003/api/blogs
Content-type: application/json

###
GET http://localhost:3003/api/users
Content-type: application/json